# Generated by Django 4.2.6 on 2023-10-09 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
