# Generated by Django 4.2.6 on 2023-10-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
