# Generated by Django 4.2.6 on 2023-10-10 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=10), django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
