# Generated by Django 4.2.6 on 2023-10-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0008_alter_title_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
